https://safe-river-04132.herokuapp.com/

Having done the task 3.11, Heroku sends out a 503 (service unavailable) error 30 seconds after the person has already been deleted. 

eq. when deleting person 1, tehy get deleted normally, but 30 seconds later this error pops up 
"DELETE https://safe-river-04132.herokuapp.com/api/persons/1 503 (Service Unavailable)"
